config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # path("users/", include("djangogram.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # /
    path("", include("djangogram.users.urls", namespace="users")),

    # /posts/
    path("posts/", include("djangogram.posts.urls", namespace="posts")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

djangogram/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # /posts/
    path('', views.index, name='index'),

    # /posts/create/
    path('create/', views.post_create, name='post_create'),

    # /posts/3/update/
    path('<int:post_id>/update', views.post_update, name='post_update'),

    # /posts/1/post_delete/
    path('<int:post_id>/post_delete', views.post_delete, name="post_delete"),

    # /posts/1/comment_create/
    path('<int:post_id>/comment_create', views.comment_create, name='comment_create'),

    # /posts/1/comment_delete/
    path('<int:comment_id>/comment_delete', views.comment_delete, name='comment_delete'),

    # /posts/5/post_like/
    path('<int:post_id>/post_like', views.post_like, name='post_like'),

    # /posts/search/
    path('search/', views.search, name='post_search'),

]

djangogram/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
]

djangogram/posts/models.py
from django.db import models
from djangogram.users import models as user_model

# Create your models here.
class TimeStamedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta: # 이 클래스를 사용하면 해당 클래스는 테이블을 만들지 않음.
        abstract = True

# 장고는 흔히 게시물 생성 시간과 수정 시간을 가짐. 각각의 클래스에 이걸 매번 추가하지 않고 시간관련 부분을 클래스로 따로 만들어서 관리하자.
# 시간관련 클래스 만들고 상속하면 됨.

class Post(TimeStamedModel):
    author = models.ForeignKey(
                user_model.User,
                null=True,
                on_delete=models.CASCADE,
                related_name= 'post_author'
            )
    image = models.ImageField(blank=False)
    caption = models.TextField(blank=False)
    image_likes = models.ManyToManyField(
                    user_model.User,
                    blank=True, # 이미지 좋아요 부분 blank를 true로 변경
                    related_name='post_image_likes'
            )

    # 모델을 구분할 수 있게 str 메서드 추가.
    def __str__(self):
        return f"{self.author}: {self.caption}"


class Comment(TimeStamedModel):
    author = models.ForeignKey(
            user_model.User,
            null=True,
            on_delete=models.CASCADE,
            related_name= 'comment_author'
        )
    posts = models.ForeignKey(
            Post,
            null=True,
            on_delete=models.CASCADE,
            related_name= 'comment_post'
        )
    contents = models.TextField(blank=True)

    # 모델을 구분할 수 있게 str 메서드 추가.
    def __str__(self):
        return f"{self.author}: {self.contents}"

djangogram/users/models.py
from asyncio.base_subprocess import WriteSubprocessPipeProto
from tokenize import blank_re
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for djangogram.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('C', 'Custom'),
    ]

    #: First and last name do not cover name patterns around the globe
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    user_name = models.CharField(blank=True, max_length=255)
    profile_photo = models.ImageField(blank=True)
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    email = models.CharField(blank=True, max_length=255)
    phone_number = models.CharField(blank=True, max_length=255)
    gender = models.CharField(blank=True, choices=GENDER_CHOICES, max_length=255)
    followers = models.ManyToManyField("self")
    following = models.ManyToManyField("self")


    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

djangogram/posts/forms.py
from django import forms
from .models import Post, Comment

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["caption", "image"] # 내용작성은 models.py 참고!

        labels = {
            "caption" : "내용",
            "image" : "사진"
        }

class UpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["caption"]

class CommentForm(forms.ModelForm):
    # label이 원래는 contents 인데 그 글자를 보여주고 싶지 않아서 contents를 재정의함.
    contents = forms.CharField(widget=forms.Textarea, label="")

    class Meta:
        model = Comment
        fields = ["contents"]

djangogram/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django import forms as django_forms

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

# 장고 폼.
class SignUpForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'name', 'username', 'password']

        # label 변경
        # labels = {
        #     'email': "이메일 주소",
        #     'name': "성명",
        #     'username': "사용자 이름",
        #     'password': "비밀번호",
        # }

        # 비밀번호 숫자가 안보이게 설정할 것. 이렇게 비밀번호 폼 따로 설정하면 비번이 안보임.
        # + input box에 placeholder 적용 위해 widgets 사용.
        widgets = {
            'email': django_forms.TextInput(attrs={'placeholder': '이메일 주소'}),
            'name': django_forms.TextInput(attrs={'placeholder': '성명'}),
            'username': django_forms.TextInput(attrs={'placeholder': '사용자 이름'}),
            'password': django_forms.PasswordInput(attrs={'placeholder': '비밀번호'}),
        }

    # 해시 알고리즘을 적용하는 코드.
    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

djangogram/posts/views.py
import pkgutil
from telnetlib import STATUS
from urllib import response
from webbrowser import get
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import JsonResponse

from djangogram.users.models import User as user_model
from . import models, serializers
from .forms import CreatePostForm, CommentForm, UpdatePostForm

# Create your views here.
def index(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            comment_form = CommentForm()

            user = get_object_or_404(user_model, pk=request.user.id) # pk = 로그인된 유저의 아이디. user_model에서 가져옴.
            following = user.following.all() # 그 유저의 모든 팔로잉 유저 가져옴.
            posts = models.Post.objects.filter(
                Q(author__in = following) | Q(author = user) # Q객체 사용해서 여러 조건 가능. or 조건 사용하기 위해 씀. feild 뒤에 '__in' 키워드 사용하면 팔로잉 유저가 여러명 있다면 해당 유저의 모든 포스트를 가져옴.
            ).order_by("-create_at")

            serializer = serializers.PostSerializer(posts, many=True) # 시리얼라이저로 모델에서 추출한 post 넘기기. 포스트는 여러개가 될 수 있으니 many=True 값 꼭 넣기!
            print(serializer.data) # 변경된 데이터 확인.

            return render(
                request,
                'posts/main.html',
                {"posts": serializer.data, "comment_form": comment_form}
            )

def post_create(request):
    # 게시물 등록을 위한 화면을 요청(GET 방식)
    if request.method == 'GET':
        form = CreatePostForm()
        return render(request, 'posts/post_create.html', {"form": form}) # template에 request와 form을 넘김.

    elif request.method == 'POST':
        if request.user.is_authenticated:
            # (user_model에서 user id를 가져와. -> 유저 객체 가져옴.)
            user = get_object_or_404(user_model, pk=request.user.id)

            # image = request.FILES['image']
            # caption = request.POST['caption']

            # # 포스트에 대한 객체 만들기
            # new_post = models.Post.objects.create(
            #     author = user,
            #     image = image,
            #     caption = caption
            # )

            # # 저장하기
            # new_post.save()

            # 요청받은 post data와 file을 form에 넘겨줌.
            form = CreatePostForm(request.POST, request.FILES)

            if form.is_valid(): # 유효성 검사 후,
                post = form.save(commit=False) # form 내용 저장. commit=false로 하면 db에 저장되지는 않음. 임시저장 느낌.
                post.author = user # post 테이블은 user가 외래키이기 때문에 반드시 명시해주어야 함.
                post.save() # db에 저장됨.
            else:
                print(form.errors)

            return redirect(reverse('posts:index'))

        else:
            return render(request, 'users/main.html')

def post_update(request, post_id):
    if request.user.is_authenticated:
        # 포스트 작성자 수정 요청 한 거 맞는지 작성자 체크
        post = get_object_or_404(models.Post, pk=post_id)
        if request.user != post.author:
            return redirect(reverse('posts:index'))

        # 맞다면 수정을 위한 페이지를 요청하는 GET방식 요청.
        if request.method == 'GET':
            form = UpdatePostForm(instance=post)
            return render(
                request,
                'posts/post_update.html',
                {"form": form, "post":post}
            )

        elif request.method == 'POST':
            # 업데이트 버튼 클릭 후 저장을 위한 POST api 요청 로직.
            form = UpdatePostForm(request.POST)
            if form.is_valid():
                post.caption = form.cleaned_data['caption']
                post.save()

            return redirect(reverse('posts:index'))

    else:
        return render(request, 'users/main.html')

def post_delete(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(models.Post, pk=post_id)
        if request.user == post.author:
            post.delete()

        return redirect(reverse('posts:index'))

    else:
        return render(request, 'users/main.html')

def comment_create(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(models.Post, pk=post_id)

        form = CommentForm(request.POST)
        if form.is_valid:
            comment = form.save(commit=False) # db에 저장 no!. 왜냐면 form에는댓글 내용만 있기 때문에 댓글 작성자와 댓글이 어느 포스트의 댓글인지에 대한 내용이 없음.
            comment.author = request.user # 댓글작성자
            comment.posts = post # 포스트
            comment.save() # db에 저장

            # 피드 페이지로 데이터 넘기기(posts앱의 index alias)
            # url 뒤에 '#' 다음에 입력된 값이 있다면 html에 그 값(id 선택자)이 있는 부분으로 스크롤이 내려감.
            return redirect(reverse('posts:index') + "#comment-" + str(comment.id))

        else:
            return render(request, 'users/main.html')

def comment_delete(request, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(models.Comment, pk=comment_id)
        if request.user == comment.author:
            comment.delete()

        return redirect(reverse('posts:index'))

    else:
        return render(request, 'users/main.html')

def post_like(request, post_id):
    # result란 key 값은 서버단과 클라이어튼 단에서 데이터 주고 받을 수 있게 약속된 걸 사용해야함. 우리만의 약속. hi라고 해도 됨. 단 맞춰주어야 함.
    response_body = {"result": ""}

    # 로그인 한 유저만 좋아요 클릴할 수 있도록 분기 처리.
    if request.user.is_authenticated:
        if request.method == "POST":

            # 현재 좋아요 상태인지 아닌지 db 조회하기.
            post = get_object_or_404(models.Post, pk=post_id)

            # 조회 조건 추가(filter 이용).
            # Post 테이블의 image_likes 컬럼은 User 모델임. 즉, user가 들어감.
            # image_likes를 조회한다 => user모델을 조회한다.
            # exists() -> user.id 가 있으면 True, 없으면 False
            existed_user = post.image_likes.filter(pk=request.user.id).exists()

            if existed_user:
                # 좋아요 누른 상태일 때는 "좋아요 취소."
                post.image_likes.remove(request.user) # db에 반영
                response_body['result'] = "dislike"
            else:
                # 좋아요가 아닐 때는 "좋아요."
                post.image_likes.add(request.user) # db에 반영
                response_body['result'] = "like"

            post.save()
            return JsonResponse(status=200, data=response_body)
    else:
        # 클라이언트에 데이터 넘겨줄 때 json 형태로 보내줘야 ajax 처리가 가능함.
        return JsonResponse(status=403, data=response_body) # 로그인 안 된 유저는 비어있는 결과값 보내기.

def search(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            searchKeyword = request.GET.get("q", "") # q키에 대한 값 가져오는 것. q 키에 대한 값이 없다면 두 번째 인자를 대신하여 받음.

            # 키워드를 검색하고 유저에게 피드 페이지를 보여주는 logic은 index logic과 굉장히 유사함!
            comment_form = CommentForm()

            user = get_object_or_404(user_model, pk=request.user.id)
            following = user.following.all()
            posts = models.Post.objects.filter(
                # 사용자가 입력한 내용이 보이게 추가해주자.
                # caption = ' ' 이렇게 입력하면 오로지 입력값과 일치한 값만 보이기 때문에,
                # __contatins 접미사를 사용하자.
                # (팔로잉한 게시물 또는 내가 작성한 게시물) and (searchKeyword가 포함된 게시물)
                (Q(author__in = following) | Q(author = user)) & Q(caption__contains=searchKeyword)
            ).order_by("-create_at")

            serializer = serializers.PostSerializer(posts, many=True) #
            print(serializer.data)

            return render(
                request,
                'posts/main.html',
                {"posts": serializer.data, "comment_form": comment_form}
            )
    else:
        return render(request, 'users/main.html')

djangogram/users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth import authenticate, login

# from djangogram.users.forms import SignUpForm
from .forms import SignUpForm

def main(request):
    if request.method == 'GET':
        return render(request, 'users/main.html')

    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('posts:index'))

        else:
            # Return an 'invalid login' error message.
            return render(request, 'users/main.html')

def signup(request):
    if request.method == 'GET':
        form = SignUpForm()

        # render한다 (request를, 'html로', {context 내용을.})
        return render(request, 'users/signup.html', {'form': form})

    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid(): # is_valid() : 장고 폼의 유효성 검사 함수.
            form.save() # user db에 데이터 저장.

            # 자동 로그인 기능 만들기.
            # 저장된 데이터 불러오기.
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # 기존에 만든 로그인 logic 가져오기.
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                # Redirect to a success page.
                return HttpResponseRedirect(reverse('posts:index'))

        return render(request, 'users/main.html')

djangogram/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" type="text/css" href="{% static 'css/posts/base.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/posts/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/posts/main.css'%}">

  <title>Document</title>

  <!-- font awesome -->
  <script src="https://kit.fontawesome.com/a34c4da7e2.js" crossorigin="anonymous"></script>
</head>
<body>
  <div class="header">
    {% include "posts/header.html" %}
  </div>
  <div>
    {% block content %} {% endblock %}
  </div>

  <script type="text/javascript" src="{% static 'js/posts.js' %}"></script>
</body>
</html>

djangogram/templates/posts/header.html
{% load static %}

<header>
  <div class="header-box">
    <div class="main-img">
      <a href="{% url 'posts:index' %}">
        <img src="{% static 'images/posts/main_logo.png'%}" alt="logo">
      </a>
    </div>
    <div class="search">
      <form action="{% url 'posts:post_search' %}" method="GET">
        <!-- 쿼리 스트링에 key 추가하기 위해 input에 name 추가.-->
        <input type="text" name="q" placeholder="Search">
      </form>
    </div>
    <div class="header-right">
      <div>
        <a href="{% url 'posts:post_create' %}">
          <i class="fa-solid fa-circle-plus" style="font-size: 1.5em;"></i>
        </a>
      </div>
      <div>
        <a href="#">
          <i class="fa-solid fa-user" style="font-size: 1.5em;"></i>
        </a>
      </div>
    </div>
  </div>
</header>

djangogram/templates/posts/index.html
Here is posts index.html
<!--  -->

djangogram/templates/posts/main.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}

{% for post in posts %}

    <!-- {{ post.author.id }}
    {{ post.author.username }}
    {{ post.author.profile_photo }}
    {{ post.id }}
    {{ post.image }}
    {{ post.caption }}

    {% for comment in post.comment_post %}
    <br> {{ comment.contents }}
    {% endfor %}

    <div>
      ------------------------------------- -->

  <div class="post-box">
    <!-- HEADER -->
    <div class="header">
      <div class="profile">
        <!-- 유저 프로필 사진이 있다면 있는 사진을, 없다면 미리 저장된 사진을 보여줌. -->
        {% if post.author.profile_photo != None %}
            <img src="{{ post.author.profile_photo }}">
        {% else %}
            <img src="{% static 'images/posts/no_avatar.png' %}">
        {% endif %}

        <div>
            <b>{{ post.author.username }}</b>
        </div>
      </div>

      <!-- 포스트 수정 & 삭제 기능 구현. 작성자만 버튼 보이게 조건문 사용함. -->
      {% if user.id == post.author.id %}
        <div class="icon">

          <!-- 포스트 수정 기능 구현 -->
          <!-- key 값인 post.id를 넘겨줌. 왜냐면 해당 내용만 삭제해야하기 때문에. -->
          <a href="{% url 'posts:post_update' post.id %}">
            <i class="fa fa-pencil fa1x"></i>
          </a>

          <!-- 포스트 삭제 기능 구현 -->
          <a href="{% url 'posts:post_delete' post.id %}">
            <i class="fa fa-trash-o fa1x"></i>
          </a>
        </div>
      {% endif %}

    </div>

    <!-- IMAGE -->
    <img class="post-image" src="{{ post.image }}">

    <!-- IMAGE-BUTTON -->
    <!-- 어떤 포스트를 좋아하는지 포스트를 식별하도록 post_id를 id 값으로 추가. -->
    <!-- 이 id값을 onclick 함수에서 넘겨받도록 인자 줌. -->
    <button id="like-button-{{ post.id }}" onclick="handleLikeClick(this.id)">
    {% if user.id in post.image_likes %}
      <i class="fa fa-heart fa-2x"></i>
    {% else %}
      <i class="fa fa-heart-o fa-2x"></i>
    {% endif %}
    </button>

    <div class="desc-box">
      <!-- IMAGE-DESCRIPTION -->
      <div class="image-desc">
        <b>{{ post.author.username }}</b>
        {{ post.caption }}
      </div>

      <hr class="line">

      <!-- COMMENT -->
      <div class="comment">
        {% for comment in post.comment_post %}
          <div id="comment-{{ comment.id }}">
            <b>{{ comment.author.username }}</b>
            {{ comment.contents }}
            <!-- 'user'라는 키워드를 그냥 사용해주면 됨. -->
            {% if user.id == comment.author.id %}
            <a href="{% url 'posts:comment_delete' comment.id %}">
              <i class="fa fa-trash-o fa1x"></i>
            </a>
            {% endif %}
          </div>
        {% endfor %}
      </div>
    </div>

    <!-- COMMENT INPUT -->
    <div class="comment-input">
      <!-- post.id 를 사용할 수 있는 이유 : 시리얼라이저에서 post의 id를 가져와서 사용한다고 명시했기 때문. -->
      <form action="{% url 'posts:comment_create' post.id %}" method="post">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit" value="Post">
      </form>

    </div>

</div>

{% endfor %}

{% endblock content %}

djangogram/templates/posts/post_create.html
{% extends "posts/base.html" %}

{% block content %}

<div class="post-create">
  <div>
    Create Post
  </div>
  <div class="form">
    <!-- 파일이나 이미지를 post로 서버에 보내는 경우 enctype을 지정해주어야 함! -->
    <form action="{% url 'posts:post_create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- views.py 에서 form 을 넘겨받음. as_p 사용하면 자동으로 html p 태그로 싸인 field 내용들이 보임.  -->
      {{ form.as_p }}
      <input type="submit" value="Create">
    </form>
  </div>
</div>

{% endblock content%}

djangogram/templates/posts/post_update.html
{% extends "posts/base.html" %}

{% block content %}

<div class="post-create">
  <div>
    Update Post
  </div>
  <div class="form">
    <form action="{% url 'posts:post_update' post.id %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Update">
    </form>
  </div>
</div>

{% endblock content%}